# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Microsoft.AzureAztfy
PackageVersion: 0.9.0
InstallerLocale: en-US
Scope: machine
UpgradeBehavior: install
Commands:
- aztfy
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/Azure/aztfy/releases/download/v0.9.0/aztfy_v0.9.0_x64.msi
  InstallerSha256: BCDEE5162DB37D8472EF4947F38F1A01C753D6A13C7ED9EE2748B6E63CE38E50
  ProductCode: '{D8F51C74-F844-4887-8940-5D80AFEB7B63}'
  AppsAndFeaturesEntries:
  - DisplayName: aztfy
    Publisher: Microsoft
    ProductCode: '{566C44B9-7312-4841-8537-0FB95CDFD2A6}'
ManifestType: installer
ManifestVersion: 1.2.0

